#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Creation Date: July 11, 2023

@author: Aaron Wilkowitz
"""

################
### import 
################
# gcp 
from google.protobuf import json_format
from google.protobuf.struct_pb2 import Value
import vertexai
from vertexai.language_models import TextGenerationModel
from vertexai.preview.language_models import ChatModel, InputOutputTextPair
from google.cloud import storage

# others 
import streamlit as st
import pandas as pd
from datetime import datetime
import datetime, pytz
import ast
import seaborn as sns

################
### page intro
################

# Make page wide
st.set_page_config(
    page_title="GCP GenAI",
    layout="wide",
  )

# Title
st.title('GCP HCLS GenAI Demo: Supply Chain PO Order - Q&A')

# Author & Date
st.write('**Author**: Aaron Wilkowitz, aaronwilkowitz@google.com')
st.write('**Date**: 2023-07-11')
st.write('**Purpose**: Hospital has many supply chain PO orders. They need to ask questions against the order')

################
### model inputs
################

# Model Inputs
st.divider
st.header('1. Model Inputs')

model_id = st.selectbox(
    'Which model do you want to use?'
    , (
          'chat-bison@001'
        , 'chat-bison@latest'
      )
    , index = 0
  )
model_temperature = st.number_input(
      'Model Temperature'
    , min_value = 0.0
    , max_value = 1.0
    , value = 0.2
  )
model_token_limit = st.number_input(
      'Model Token Limit'
    , min_value = 1
    , max_value = 1024
    , value = 100
  )
model_top_k = st.number_input(
      'Top-K'
    , min_value = 1
    , max_value = 40
    , value = 40
  )
model_top_p = st.number_input(
      'Top-P'
    , min_value = 0.0
    , max_value = 1.0
    , value = 0.8
  )

################
### data
################

# Prompt Inputs
st.divider
st.header('2. Data')

# Goal
order_id = st.selectbox(
    'What order do you want to learn about?'
    , (
          'order1'
        , 'order2'
        , 'order3'
      )
    , index = 0
  )

st.write(':blue[**Order:**] ' + order_id)

# Download File -- Fill this out later
# if order_id == "order1":
#   file_data = "synthetic-bariatric-ccda-full-9580-lines.xml"
# elif order_id == "order2":
#   file_data = "synthetic-bariatric-ccda-full-9580-linesv2.xml"
# elif order_id == "order3":
#   file_data = "synthetic-bariatric-fhir-full-24527-lines.json"
# else:
#   file_data = "unknown"

# project_id = "cloudadopt"
# location_id = "us-central1"
# bucket_name = "hcls_genai"
# client = storage.Client()
# bucket = client.bucket(bucket_name)
# blob = str(bucket.blob(file_name).download_as_string())
# st.write(':green[**Complete**] File Downloaded')

# blob_sample = blob[:1000]
# st.write(':blue[**File Sample:**] ' + blob_sample)

order_data = """---------------------------------------------------------( PURCHASE ORDER )---------------------------------------------------------

02-09-2023             : SOUTHERN HILLS HOSP                                   : SOUTHERN HILLS MED CTR        PO NUMBER:     815117
00:35 AM       BILL TO : 245 B GREAT CIRCLE ROAD                       SHIP TO : 391 WALLACE ROAD
                       :                                                       :                                 PO DATE: 02-08-2023
                       : NASHVILLE                  TN  US   37228             : NASHVILLE       TN372114851        PAGE:    1
------------------------------------------------------------------------------------------------------------------------------------
 VENDOR: 947744   ** EDI **     CUST NO: 296501:0001          TERMS: NET 30 days                    DISC:   .00 DAYS: 00
                  ** EDI **
     EHOB INC                          CONTACT:                                SHIP VIA: SUPPLIERS CHOICE           COID   : 34242
     250 N BELMONT AVENUE                PHONE: (800) 899-5553                FAX PHONE: 1(317) 972-4601            BUYER  : RLU6982
                                           EXT:                                     EXT:                            MIN AMT:      0
     INDIANAPOLIS                   IN     FOB: DESTINATION,PREPAY & ADD      CYCLE/DAY:   3 / M_W____              MIN QTY:      0
                               US 46222
------------------------------------------------------------------------------------------------------------------------------------
LINE DEPT ACCT    ITEM        DESCRIPTION                QTY  PU REC1   REC2   REORDER NUMBER       TAX CC   UNIT COST    TOTAL COST
------------------------------------------------------------------------------------------------------------------------------------
  1 0610 00610425 002175269 PROTECTOR HEEL TRUVUE LITE     1  CA _____  _____  TRUVUELT6                C      192.000      192.00



         VO#00557580;DT020823"""

st.write(':blue[**Order Data:**] ' )
st.write(order_data)

################
### LLM prompt & output
################

# Prompt Inputs
st.divider
st.header('3. LLM Prompt & Output')

custom_prompt = st.text_input('Write your question here')

# Run the model

project_id = "cloudadopt"
location_id = "us-central1"

import vertexai
from vertexai.preview.language_models import ChatModel, InputOutputTextPair

vertexai.init(
      project = project_id
    , location = location_id)
chat_model = ChatModel.from_pretrained(model_id)
parameters = {
    "temperature": 0.2,
    "max_output_tokens": 256,
    "top_p": 0.8,
    "top_k": 40
}
chat = chat_model.start_chat(
    context=order_data,
)
response = chat.send_message(custom_prompt, **parameters)
# print(f"Response from Model: {response.text}")
llm_response_text = response.text 
st.write(':blue[**LLM Response:**] ' + llm_response_text)
